### ISSUE TITLE
Try this project on nexys A7

### ISSUE THREAD

**Issue by danielitzahi** [ZipCPU/openarty#5]
Hi dan
I allready finished your project icozip on (iCE40HX8K) board
And i think to start this project on "nexys A7" it's available for me i also know that is not simeler board
   Eth phy is RMII
   The sdram is ddr2

In your opinion, it should be a complicated job for a student?

Best regards 
Tzahi

**Comment by ZipCPU** [comment]
Well, the job is certainly doable.  Too hard for a student?  I don't know.  Might depend on how motivated you are.

The DDR2 controller is simple enough--use Xilinx's.  You'll only need to modify one or two files, and the modifications should be minimal.

The OpenArty design already supports RMII, so porting it to a new board should be highly doable and might require no more than switching up the pin connections in the XDC file.

Dan

**Comment by danielitzahi** [comment]
Thanks for your response
I'm obviously motivated
Dan
"nexys A7" as different PHY "LAN8720"
How can your OpenArty wb>MII driver deel with RMII
(4bit>2bit ) do i need to make newone ?
Tzahi

**Comment by ZipCPU** [comment]
B/c the OpenArty driver is RMII, not MII.  The number of data wires is 4, they're just clocked on both edges of the clock--that's the difference between RMII and MII.

**Comment by danielitzahi** [comment]
Dan
So from whare the mac core
get the clk 50Mhz 
From mii rxclk,txclk?
I am confused little bit ,sorry 
Tzahi

**Comment by ZipCPU** [comment]
Ok, you're right, what I have is an MII interface.  (The Nexys Video had the reduced interface, to get to GbE.)  You don't need a 50MHz clock for it, you need a 25MHz clock.  You actually need two.  These will come from the PHY chip on your board, if your PHY is anything like the Arty's.  On the Arty, this PHY also requires a 25MHz reference.  You can get that from simply dividing down your system clock.  (Use a PLL!)

With MII, you have 4 data pins and the 25Mhz clock.  That makes the 100Mb/s interface used.

Dan
